export enum EnumSysTable {
    const = '$const_str',
    setting = '$setting',
    entity = '$entity',
    version = '$version',
    phrase = '$phrase',
    site = '$site',
    id_u = '$id_u',
    id_uu = '$id_uu',
    bizPhrase = 'bizphrase',
    bizBudShow = 'bizbudshow',
    ixBizPhrase = 'ixbizphrase',

    unit = '$unit',
    user = '$user',
    userSite = '$usersite',
    ixRole = '$ixrole',

    ixState = 'ixstate',
    atom = 'atom',
    atomUnique = 'atomunique',
    spec = 'spec',
    bud = 'bud',
    duo = 'duo',
    combo = 'combo',
    ixBud = 'ixbud',
    ixBudDec = 'ixbuddec',
    ixBudInt = 'ixbudint',
    ixBudStr = 'ixbudstr',
    ixBudCheck = 'ixbudcheck',
    ixBudJson = 'ixbudjson',
    bizBin = 'bin',
    bizSheet = 'sheet',
    bizDetail = 'detail',
    pend = 'pend',
    binPend = 'binpend',
    history = 'history',

    // IO
    IOQueue = 'ioqueue',
    IOInOut = 'ioinout',
    IOError = 'ioerror',
    // IOEndPoint = 'ioendpoint',
    IOAppAtom = 'ioappatom',
    IOSiteAtomApp = 'iositeatomapp',

    messageQueue = '$message_queue',
    messageQueueEnd = '$message_queue_end',
    messageQueueFailed = '$message_queue_failed',

    // obsolete
    admin = '$admin',
    sheet = '$sheet',
    sheetDetail = '$sheet_detail',
    sheetTo = '$sheet_to',
    archive = '$archive',
    archiveFlow = '$archive_flow',
    flow = '$flow',
    fromNew = '$from_new',
    fromNewBad = '$from_new_bad',

    importDataMap = '$import_data_map',
    importDataSourceEntity = '$import_data_source_entity',
}
